#!/bin/bash
    
    if [ ! -z $SUDO_USER ]; then
        userid=$SUDO_USER
    elif [ ! -z $USER ]; then
        userid=$USER
    else
        #user가 없을 때는 실행하지 않음
        exit 0
    fi
    # postinst에서 파일이동 등으로 지워지지 않은 파일 삭제
    sudo rm -rf /home/$userid/.wine
    sudo rm /usr/share/applications/kakaotalk.desktop
	exit 0


